---
services:
  mysql:
    container_name: monitoring-mysql
    image: mysql:latest
    restart: always
    environment:
      TZ: ${TZ:-UTC}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD:-RootPassword}
    volumes:
      - ./mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysql", "-h", "127.0.0.1", "-u", "root", "--password=${MYSQL_ROOT_PASSWORD}", "-e", "show databases;"]
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 55
    
  memcached:
    container_name: "monitoring-memcached"
    image: memcached
    restart: always
    environment:
      TZ: ${TZ:-UTC}
    command:
      - --conn-limit=1024
      - --memory-limit=32
      - --threads=4
    
  server:
    container_name: "monitoring-server"
    image: "akeb/monitoring:latest"
    restart: always
    environment:
      TZ: ${TZ:-UTC}
      NGINX_PORT: ${NGINX_PORT:-80}
      MYSQL_HOST: mysql
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-RootPassword}
      MEMCACHED_HOST: ${MEMCACHED_HOST:-memcached}
      PASSWORD_SALT: ${PASSWORD_SALT:-bHchLzC3B99Ss1213127fdw876EDghc2gkDdtg}
    volumes:
      - ./logs/php/:/var/log/php/:rw
      - ./logs/nginx/:/var/log/nginx/:rw
    ports:
      - "${NGINX_PORT:-80}:80"
    depends_on:
      mysql:
        condition: service_healthy
      memcached:
        condition: service_started

